# Generated by Django 3.2.9 on 2021-11-20 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 15, 5, 8, 120544, tzinfo=utc), help_text='作成日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 15, 5, 21, 828222, tzinfo=utc), help_text='更新日'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='Markdown形式で書いてください。', verbose_name='本文'),
        ),
    ]
