# Generated by Django 3.2.9 on 2021-11-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211121_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.SlugField(default=999, unique=True),
            preserve_default=False,
        ),
    ]
